Repository blish-hud/bhud-pkgs, pull requests merged in 2022-03, with the labels that each got.

#124 Added Event Table 1.1.0
  manifests/estreya/bh/eventTable/1.1.0.json
Labels: new version

#126 Events and Metas Observer Release v0.9.1
  manifests/bh/general/events/0.9.1.json
Labels: new version

#127 Universal Search Release v0.7.0
  manifests/bh/general/universalsearch/0.7.0.json
Labels: new version

#129 Added Event Table 1.2.0
  manifests/estreya/bh/eventTable/1.2.0.json
Labels: new version

#115 add notes
  manifests/Nekres/Notes/0.3.7.json
Labels: new version

#134 Event Table Release v1.3.0
  manifests/estreya/bh/eventTable/1.3.0.json
Labels: new version

#138 Event Table Release v1.3.2
  manifests/estreya/bh/eventTable/1.3.2.json
Labels: new version

#146 Blishpad Release v1.0.2
  manifests/Snaid1/Blishpad/1.0.2.json
Labels: new version

#140 Revamped Commander's Quire
  manifests/Nekres/Notes/0.4.7.json
Labels: new version

#132 SquadTracker v0.1.2
  manifests/Torlando/SquadTracker/0.1.2.json
Labels: new version

#149 Event Table Release v1.4.0
  manifests/estreya/bh/eventTable/1.4.0.json
Labels: new version

#151 Clock 1.2.1
  manifests/Manlaan/Clock/1.2.0.json
  manifests/Manlaan/Clock/1.2.1.json
Labels: new version, module cleanup

#154 Blishpad Release v1.0.3
  manifests/Snaid1/Blishpad/1.0.3.json
Labels: new version

#155 Event Table Release v1.4.2
  manifests/estreya/bh/eventTable/1.4.2.json
Labels: new version

#157 Screenshot Manager Release v0.3.5
  manifests/Nekres/Screenshot_Manager/0.3.5.json
Labels: brand new module

#158 Blishpad Release v1.1.1
  manifests/Snaid1/Blishpad/1.1.1.json
Labels: new version

#159 Screenshot Manager Release v0.3.7
  manifests/Nekres/Screenshot_Manager/0.3.7.json
Labels: new version

#160 Blishpad Release v1.1.2
  manifests/Snaid1/Blishpad/1.1.2.json
Labels: new version

#161 Pathing Release v0.17.6
  manifests/bh/community/pathing/0.17.6.json
Labels: new version

#164 Blishpad Release v1.1.3
  manifests/Snaid1/Blishpad/1.1.3.json
Labels: new version

#171 Screenshot Manager Release v0.3.9
  manifests/Nekres/Screenshot_Manager/0.3.9.json
Labels: new version

#174 HPGrid 1.0.5
  manifests/Manlaan/HPGrid/1.0.5.json
Labels: new version

#175 Events and Metas Observer Release v0.9.2
  manifests/bh/general/events/0.9.2.json
Labels: new version

#166 Guild_Missions 1.5.2
  manifests/entrhopi/Guild_Missions/1.5.2.json
Labels: new version

#170 Mumble Info Release v0.2.9
  manifests/Nekres/Mumble_Info/0.2.9.json
Labels: new version

#179 Inquest Chipset Release v0.1.9
  manifests/Nekres/Inquest_Module/0.1.9.json
Labels: new version

#180 Characters Release v0.1.4
  manifests/Kenedia/Modules/Characters/0.1.4.json
Labels: brand new module

#183 Pathing Release v0.18.1
  manifests/bh/community/pathing/0.18.1.json
Labels: new version

#182 Inquest Chipset Release v0.2.4
  manifests/Nekres/Inquest_Module/0.2.4.json
Labels: new version

#184 Pathing Release v0.18.2
  manifests/bh/community/pathing/0.18.2.json
Labels: new version

#188 Characters Release v0.1.8
  manifests/Kenedia/Modules/Characters/0.1.8.json
Labels: new version

#189 Screenshot Manager Release v0.4.3
  manifests/Nekres/Screenshot_Manager/0.4.3.json
Labels: new version

#190 Inquest Chipset Release v0.2.6
  manifests/Nekres/Inquest_Module/0.2.6.json
Labels: new version

#193 Inquest Chipset Release v0.3.0
  manifests/Nekres/Inquest_Module/0.3.0.json
Labels: new version

#191 Characters Release v0.1.9
  manifests/Kenedia/Modules/Characters/0.1.9.json
Labels: new version

#192 Screenshot Manager Release v0.4.4
  manifests/Nekres/Screenshot_Manager/0.4.4.json
Labels: new version

#194 Pathing Release v0.18.4
  manifests/bh/community/pathing/0.18.4.json
Labels: new version
