Repository blish-hud/bhud-pkgs, pull requests merged in 2022-01, with the labels that each got.

#86 Add StreamOut v0.5.1
  manifests/Nekres/Stream_Out/0.5.1.json
Labels: new version

#87 clear guild emblem if guild has no emblem
  manifests/Nekres/Stream_Out/0.5.2.json
Labels: new version

#89 Added Pathing v0.17.0
  manifests/bh/community/pathing/0.17.0.json
Labels: new version

#90 Delete 0.17.0.json
  manifests/bh/community/pathing/0.17.0.json
Labels: module cleanup

#92 Added Event Table 0.1.8
  manifests/estreya/bh/eventTable/0.1.8.json
Labels: new version

#93 Added UpdateModule v1.0.2
  manifests/bh/community/updatemodule/1.0.2.json
Labels: brand new module

#94 assert guild emblem layer sizes and scale
  manifests/Nekres/Stream_Out/0.5.3.json
Labels: new version

#95 Added Pathing v0.17.3
  manifests/bh/community/pathing/0.17.3.json
Labels: new version

#97 Added Event Table 0.1.9
  manifests/estreya/bh/eventTable/0.1.9.json
Labels: new version

#98 MouseCursor 2.2.0
  manifests/Manlaan/MouseCursor/2.2.0.json
Labels: new version

#96 Add Mistwar v0.4.0
  manifests/Nekres/Mistwar/0.4.0.json
Labels: new version

#99 Blishpad 0.1.2
  manifests/Snaid1/Blishpad/0.1.2.json
Labels: brand new module

#102 Mounts 1.2.2
  manifests/Manlaan/Mounts/1.2.2.json
Labels: new version
