Repository blish-hud/bhud-pkgs, pull requests merged in 2023-02, with the labels that each got.

#464 Special Forces Release v0.4.12
  manifests/Nekres/RotationTrainer/0.4.12.json
Labels: new version

#466 Stream Out Release v0.7.9
  manifests/Nekres/Stream_Out/0.7.9.json
Labels: new version

#469 Builds Manager Release v0.0.23
  manifests/Kenedia/Modules/BuildsManager/0.0.23.json
Labels: new version

#470 Live Map Release v0.10.0
  manifests/estreya/bh/liveMap/0.10.0.json
Labels: new version

#468 Racing Meter Release v1.8.0-beta
  manifests/Ideka/RacingMeter/1.8.0-beta.json
Labels: new version

#471 Quill of the Mists Release v2.3.0
  manifests/Ideka/MistsQuill/2.3.0.json
Labels: new version

#472 Racing Meter Release v1.8.2-beta
  manifests/Ideka/RacingMeter/1.8.2-beta.json
Labels: new version

#473 Live Map Release v1.0.0
  manifests/estreya/bh/liveMap/1.0.0.json
Labels: new version

#475 Event Table Release v2.2.0
  manifests/estreya/bh/eventTable/2.2.0.json
Labels: new version

#477 Characters Release v1.0.0
  manifests/Kenedia/Modules/Characters/1.0.0.json
Labels: new version

#478 Characters Release v1.0.1
  manifests/Kenedia/Modules/Characters/1.0.1.json
Labels: new version

#480 Characters Release v1.0.2
  manifests/Kenedia/Modules/Characters/1.0.2.json
Labels: new version

#481 Characters Release v1.0.3
  manifests/Kenedia/Modules/Characters/1.0.3.json
Labels: new version

#479 RELEASE TEH CHOYA! Release v0.0.3
  manifests/Kenedia/Modules/ReleaseTheChoya/0.0.3.json
Labels: brand new module

#482 Characters Release v1.0.4
  manifests/Kenedia/Modules/Characters/1.0.4.json
Labels: new version

#485 Characters Release v1.0.6
  manifests/Kenedia/Modules/Characters/1.0.6.json
Labels: new version

#486 Event Table: Remove old non ssrd versions
  manifests/estreya/bh/eventTable/0.1.7.json
  manifests/estreya/bh/eventTable/0.1.9.json
  manifests/estreya/bh/eventTable/0.2.0.json
  manifests/estreya/bh/eventTable/1.0.1.json
  manifests/estreya/bh/eventTable/1.1.0.json
Labels: module cleanup

#487 Event Table Release v2.3.0
  manifests/estreya/bh/eventTable/2.3.0.json
Labels: new version

#488 Clears Tracker Release v2.0.1
  manifests/Soeed/RaidClears/2.0.1.json
Labels: new version

#489 Clears Tracker Release v2.0.2
  manifests/Soeed/RaidClears/2.0.2.json
Labels: new version

#490 Event Table Release v2.4.0
  manifests/estreya/bh/eventTable/2.4.0.json
Labels: new version

#491 Characters Release v1.0.7
  manifests/Kenedia/Modules/Characters/1.0.7.json
Labels: new version

#492 Session Tracker Release v1.3.0
  manifests/ecksofa/sessiontracker/1.3.0.json
Labels: new version

#494 Unda Da Sea Release v2.0.2
  manifests/Taimi/UndaDaSea_BlishHUD/2.0.2.json
Labels: new version

#495 Pathing Release v1.1.13
  manifests/bh/community/pathing/1.1.13.json
Labels: new version

#496 Characters Release v1.0.8
  manifests/Kenedia/Modules/Characters/1.0.8.json
Labels: new version

#497 Event Table Release v2.5.0
  manifests/estreya/bh/eventTable/2.5.0.json
Labels: new version

#498 Characters Release v1.0.9
  manifests/Kenedia/Modules/Characters/1.0.9.json
Labels: new version

#499 Event Table Release v2.5.1
  manifests/estreya/bh/eventTable/2.5.1.json
Labels: new version

#500 Event Table Release v2.5.2
  manifests/estreya/bh/eventTable/2.5.2.json
Labels: new version

#501 Characters Release v1.0.10
  manifests/Kenedia/Modules/Characters/1.0.10.json
Labels: new version

#503 Live Map Release v1.1.0
  manifests/estreya/bh/liveMap/1.1.0.json
Labels: new version

#502 Event Table Release v2.5.3
  manifests/estreya/bh/eventTable/2.5.3.json
Labels: new version

#506 Scrolling Combat Text Release v1.1.0
  manifests/estreya/bh/scrollingCombatText/1.1.0.json
Labels: new version

#505 Music Mixer Release v0.9.16
  manifests/Nekres/Music_Mixer/0.9.16.json
Labels: new version

#510 Event Table Release v3.0.0
  manifests/estreya/bh/eventTable/3.0.0.json
Labels: new version

#511 Achievement Tracker Release v0.1.6
  manifests/Denrage/AchievementTrackerModule/0.1.6.json
Labels: new version

#512 Player Marker Release v1.0.1
  manifests/Tortle/PlayerMarker/1.0.1.json
Labels: brand new module

#513 Event Table Release v3.0.1
  manifests/estreya/bh/eventTable/3.0.1.json
Labels: new version

#514 Event Table Release v3.0.2
  manifests/estreya/bh/eventTable/3.0.2.json
Labels: new version

#515 Live Map Release v1.2.0
  manifests/estreya/bh/liveMap/1.2.0.json
Labels: new version

#516 Player Marker Release v1.1.0
  manifests/Tortle/PlayerMarker/1.1.0.json
Labels: new version

#518 Music Mixer Release v0.9.18
  manifests/Nekres/Music_Mixer/0.9.18.json
Labels: new version

#520 Clears Tracker Release v2.0.3
  manifests/Soeed/RaidClears/2.0.3.json
Labels: new version

#522 Pathing Release v1.1.15
  manifests/bh/community/pathing/1.1.15.json
Labels: new version

#519 Event Table Release v3.0.3
  manifests/estreya/bh/eventTable/3.0.3.json
Labels: new version

#523 Characters Release v1.0.11
  manifests/Kenedia/Modules/Characters/1.0.11.json
Labels: new version
